// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyrPbQY443S0EXwqyZJFiSbcdfFYEQlU8',
    appId: '1:801504136659:web:ee887e9731ea0a68f4f326',
    messagingSenderId: '801504136659',
    projectId: 'news-app-675ee',
    authDomain: 'news-app-675ee.firebaseapp.com',
    storageBucket: 'news-app-675ee.appspot.com',
    measurementId: 'G-94BQJHEEDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjAb46jNiPaix-qViIkW8SeVnW5fkkHdM',
    appId: '1:801504136659:android:2472d717a4a7e3c6f4f326',
    messagingSenderId: '801504136659',
    projectId: 'news-app-675ee',
    storageBucket: 'news-app-675ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOPVXnjTnd7onOPcQGy9SXcr59vIWhQOE',
    appId: '1:801504136659:ios:a7b6d529f26093d7f4f326',
    messagingSenderId: '801504136659',
    projectId: 'news-app-675ee',
    storageBucket: 'news-app-675ee.appspot.com',
    iosBundleId: 'com.example.newsConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOPVXnjTnd7onOPcQGy9SXcr59vIWhQOE',
    appId: '1:801504136659:ios:a7b6d529f26093d7f4f326',
    messagingSenderId: '801504136659',
    projectId: 'news-app-675ee',
    storageBucket: 'news-app-675ee.appspot.com',
    iosBundleId: 'com.example.newsConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyrPbQY443S0EXwqyZJFiSbcdfFYEQlU8',
    appId: '1:801504136659:web:7156fe4a267d3c3ff4f326',
    messagingSenderId: '801504136659',
    projectId: 'news-app-675ee',
    authDomain: 'news-app-675ee.firebaseapp.com',
    storageBucket: 'news-app-675ee.appspot.com',
    measurementId: 'G-SJM3KRZ7T6',
  );
}
